### PR TITLE
Added shouldBeEquivalentTo and shouldNotBeEquivalentTo functionality

### PR DESCRIPTION
**Pull request by drcolombo**
Description
Added shouldBeEquivalentTo and shouldNotBeEquivalentTo functionality instructing Kluent how to compare objects. By default it will do comparison by each and every non-private property instead of using equals() method.

- You can define list of properties to include in comparison or to exclude some of them
- For object hierarchies you can define how deep the level of recurrsion should be (the default value is 10)
- For iterables you can define if you want to perform comparison keeping the same order or in any order

Checklist

- [X ] I've added my name to the `AUTHORS` file, if it wasn't already present.

### CODE REVIEW

**Comment by drcolombo** [comment]
Looks like only the project admin may run SonarCube analysis.

**Comment by MarkusAmshove** [comment]
Oh I didn't know that, I'll look if I can change the permissions.

I'll also review the changes later this week or at the weekend.
After our email conversation and  my first look into the diff here I think I'm in favor of not touching the assertions that we already have and implement the new ones you already built 👍

**Comment by MarkusAmshove** [comment]
I had a look at the changes and assertions and I'm ready to merge :+1: 

Would you be willing to add a small documentation about the assertion (especially its options) in the docs/ folder? I think that would help the discovery of this cool assertion :-)

**Comment by drcolombo** [comment]
Sure - will do it tomorrow.

**Comment by drcolombo** [comment]
Let me know if you have any concerns about the created documentation.

**Comment by MarkusAmshove** [comment]
Thank you very much again :-) This is now released under v1.64 :-)

**Pull request merged**
