### PR TITLE
Declare contracts whenever possible

### LINKED ISSUE #125: Declare kotlin 1.3 contracts
There are few assertions which would benefit from Kotlin 1.3 contracts.

Here is an example with `shouldNotBeNull()`:

```kotlin
fun <T : Any> T?.shouldNotBeNull(): T {
  contract {
    returns() implies (this@shouldNotBeNull != null)
  }

  return this ?: throw AssertionError("Expected non null value, but value was null")
}
```

This allows the following:

```kotlin
@Test
fun testSomething() {
  val x = foo()
  x.shouldNotBeNull()
  x.callSomething() // <-- Smart cast by the Kotlin compiler
}
```

If you're interested, I'd be happy to open a PR

### PR DESCRIPTION
**Pull request by jcornaz**
### Description
Declare kotlin 1.3 contracts where it may allow the compiler to smart cast something to a non-nullable type.

Resolve #125 

I added contracts for
* `shouldNotBeNull` and its bactick equivalent
* `shouldBeTrue`, `shouldBeFalse`, `shouldNotBeTrue`, `shouldNotBeFalse` and their bactick equivalents
* `shouldNotBeNullOrEmpty` and `shouldNotBeNullOrBlank`() and their bactick equivalents

I did not add contracts for:
* `T.should(assertion: T.() -> Boolean): T`  (lambda executed in-place exactly once)
  * There seem to be a bug in the compiler when using it. Maybe because of the generic type receiver. I will investigate and report the issue.
* `{ } shouldThrow Exception::class` and equivalents (lambda executed in-place exactly once)
  * This is because the lambda has to be declared *before* the function call, the kotlin compiler is not able to use any contract here.
* `Any.shouldBeInstanceOf<T>()`. (returns implies `this is T`)
  * The contract API does not support checks agains generic type (even reified) at the moment.

### Checklist
- [x] I've added my name to the `AUTHORS` file, if it wasn't already present.

### CODE REVIEW

**Comment by jcornaz** [comment]
In order to make the build pass, we have to run the compiler "-Xuse-experimental=kotlin.contracts.ExperimentalContracts". 

But I don't know how to pass arguments to the compiler in the case of Kotlin/Native.... (I'm looking for a solution)

**Comment by jcornaz** [comment]
The Kotlin/Native compiler doesn't seem to support contracts yet. It compiles successfully the contract declarations, but they have no effect. So I moved the contract tests to the JVM module.

**Comment by MarkusAmshove** [comment]
> The Kotlin/Native compiler doesn't seem to support contracts yet. It compiles successfully the contract declarations, but they have no effect. So I moved the contract tests to the JVM module.

Did the tests fail for native?

**Comment by MarkusAmshove** [comment]
This is part of the just released v1.44

**Pull request merged**
