### PR TITLE
Update Mockint.kt to include implementation of itReturnsConsecutively

### PR DESCRIPTION
**Pull request by Nescafemix**
Description
the itReturns method doesn't let to return multiple values (something that Mockito resolve with an implementation of thenReturn(firstvalue, array_of_next_values))

Expected result:
we can return several values in case we need it

example: 
When calling mockView.isReady itReturnsConsecutively  listOf(true, false)

Checklist

- [x] I've added my name to the `AUTHORS` file, if it wasn't already present.

### CODE REVIEW

**Comment by MarkusAmshove** [comment]
Hi @Nescafemix . thank you for your contribution :-)

Could you add a test to showcase how to use this? When there are questions about a certain assertion/feature, I'd like to guide people to the test.
Otherwise looking good!

**Comment by Nescafemix** [comment]
> Hi @Nescafemix . thank you for your contribution :-)
> 
> Could you add a test to showcase how to use this? When there are questions about a certain assertion/feature, I'd like to guide people to the test.
> Otherwise looking good!

Sure :). Let me check it tomorrow and do it :)

**Comment by jcornaz** [comment]
Hi all, 

Weren't mocking features about to be removed in Kluent 2.0?

(see #73, #75 and https://github.com/MarkusAmshove/Kluent/issues/75#issuecomment-355556532)

**Comment by MarkusAmshove** [comment]
I'm currently evaluating the move to 2.0 and consider adding an additional artifact to move all the mocking related stuff into.
So this PR would still be valid in this form for 1.x and when moving to 2.x I would love all the stuff to, e.g. `kluent-mockito`. That way they can coexist and current code doesn't break, just needing to depend on a different artifact

**Comment by MarkusAmshove** [comment]
Mocking will be removed in the future (once Kotlin Multiplatform is considered stable), so I'll close this PR.
Sorry for the time you've already spend on this.
I'll revisit PRs and Mocking once upgraded and think about a module system that allows Kluent to ship an artifact for mockito.

**Pull request closed without merging**
