### PR TITLE
Backtick mocking

### PR DESCRIPTION
**Pull request by mrobakowski**
Hi @MarkusAmshove!

First, I wanted to thank you for your cool library! I'm using it currently at work. I noticed some things that could be improved, so I forked it. Here are the things I changed:
* added backtick methods to the mocking API to be in line with the backtick assertion methods
* fixed the inability to compare with nulls (all your assertions were taking non-nullable parameters)

I also needed to use the new version of Mockito, so I updated the dependency... Probably should've done something smarter, since the code works well with both the old and the new version of Mockito, but I'm not skilled enough in gradle and/or maven :disappointed:.

### CODE REVIEW

**Comment by MarkusAmshove** [comment]
Hi @mrobakowski,

thanks for your pull request!

Your changes look really, I'll merge them in and release a new version (1.6).

Do you know if I also have to update the Kotlin version, or if it is fully backwards compatible?

**Comment by mrobakowski** [comment]
I've had no problem using the library with Kotlin 1.0.3 (compiler, IntelliJ plugin and stdlib). No idea weather the library compiled with 1.0.3 would work in 1.0.0, though. It probably would, since it's still an ordinary jar + some Kotlin metadata.

**Comment by Egorand** [comment]
Hi @mrobakowski, 

Backtick assertions are great, thanks a lot for that! I noticed they're not mentioned in README, could you add some info there please?

**Comment by MarkusAmshove** [comment]
Hello @mrobakowski,

I'll get to the documentation/README tomorrow, as I'm currently not at home :-)

**Pull request merged**
