### PR TITLE
Add shouldBeInRange for ClosedRanges #119

### PR DESCRIPTION
**Pull request by javatarz**
# Description
Completes open issue #119 by implementing `ClosedRange<T>.shouldBeInRange(ClosedRange<T>)`.

Also adds JVM support for backtick version.
Already a contributor so no addition to the `AUTHORS` file :)

# Checklist

- [x] I've added my name to the `AUTHORS` file, if it wasn't already present.

### CODE REVIEW

**Comment by MarkusAmshove** [comment]
Thank you for the contribution!
Could you consider to also add `shouldNotContain`, so that we have them together from the start?
That would be great :-)

**Comment by javatarz** [comment]
Hey @MarkusAmshove, @Kshitij09 has helped me out in implementing `shouldNotContain`. I've merged his PR and added him to the Authors list.

Can you have a look at this PR before merging?

**Comment by MarkusAmshove** [comment]
Thank you, I've merged it and put it onto my todo list for 1.60.
I'll give it a few days to see if I can also include #174 otherwise I'll release it :)

**Comment by MarkusAmshove** [comment]
This is now part of v1.60

**Pull request merged**
