### PR TITLE
Implement top level "invoking" function to chain throwable assertions

### PR DESCRIPTION
**Pull request by rubengees**
This implements the second proposal in #111. The tests have been adjusted to showcase the new syntax. This is basically what @aerb suggested.

- [x] I've added my name to the `AUTHORS` file, if it wasn't already present.

### CODE REVIEW

**Comment by MarkusAmshove** [comment]
Thanks for the contribution, this looks good!

I'm currently on mobile so I can't test it out, but does this change break existing code? 
From the diff it doesn't look like the `invoking` is needed, which is good for existing code  :-)

**Comment by rubengees** [comment]
No, it's completely optional 🙂

**Comment by MarkusAmshove** [comment]
Thank you, I've reviewed it and it works fine :-)

I'll release it this weekend, as I want to see if I can update the Gradle build with some of the new kotlin stuff they released

**Comment by MarkusAmshove** [comment]
It is now part of 1.47 🚢

**Pull request merged**
