### PR TITLE
#178: added support for assertSoftly

### PR DESCRIPTION
**Pull request by drcolombo**
Added support for assertSoftly notation (#178 ) based on the logic from [Kotest](https://github.com/kotest/kotest)

### CODE REVIEW

**Comment by drcolombo** [comment]
No idea how SonarCloud verifies the coverage, but locally UserStackTraceConverter.kt is covered for 100% (methods and lines) and in stacktraces.kt 100% of methods are covered and 80% of lines...
Screenshot 2020-11-17 155058

**Comment by MarkusAmshove** [comment]
Thank you for the PR, this looks really useful and I'm willing to merge it!

I'm a bit hesitant on the "based on the logic from Kotest" part, do you know which parts/files you've taken from Kotest so we can add the proper attribution in the README? Kotest has the Apache license, so it should be fine to add the proper attribution and use it :-)

**Comment by drcolombo** [comment]
> which parts/files you've taken from Kotest so we can add the proper attribution in the README? Kotest has the Apache license, so it should be fine to add the proper attribution and use it (I can do it after the merge if I know which files are based or copied from Kotest) :-)

1. ErrorCollector.kt and StackTraces.kt in all 3 modulesö
2. UserStackTraceConverter.kt
I've copied these files from Kotest almost without changes (just cosmetic ones have been added and some refactoring so their code would be compatible with Kluent).
I've also moved all tests from org.amshove.kluent into org.amshove.kluent.tests package, as the logic within StackTraces that removes stacktrace items related to the Kluent code from the stack relies on the namespace.

**Comment by drcolombo** [comment]
Tomorrow I'll provide additional code changes (didn't notice that kotlin.test.assert* were still used internally in Kluent) and updated documentation. So please, do not merge until further notice 😉

**Pull request merged**
