### PR TITLE
Added method to check if method wasn't called

### PR DESCRIPTION
**Pull request by miszmaniac**
Added method to check if method wasn’t called with specified params

### CODE REVIEW

**Comment by MarkusAmshove** [comment]
Hi @miszmaniac ,

thank you for your contribution! I'll have it reworked and merged/released within this week. I'm at bit busy at the moment :-)

**Comment by MarkusAmshove** [comment]
I've released this within version 1.22.

Thank you again!

**Comment by miszmaniac** [comment]
Thank you... this is pretty cool library, I was having difficulty reading those line in at first time, because I thought I was reading comments to code:)

I think I'll need more features like that, so I'm hoping to send you some more in future!

**Comment by MarkusAmshove** [comment]
That is awesome. That is also how I started and grew the project, adding features as I needed them :-)

**Pull request merged**
