### PR TITLE
WIP: Introduce numerical comparisons

### PR DESCRIPTION
**Pull request by MarkusAmshove**
Issue: [#17](https://github.com/MarkusAmshove/Kluent/issues/17)

- [x] shouldBeGreaterOrEqualTo
- [x] shouldBeGreaterThan
- [x] shouldBeLessOrEqualTo
- [x] shouldBeLessThan
- [x] shouldBePositive
- [x] shouldBeNegative
- [x] shouldBeInRange

### CODE REVIEW

**Comment by MarkusAmshove** [comment]
I'm finished implementing those methods.

What do you think @goreRatzete  ?

You can see those "in action" in the unittests:
https://github.com/MarkusAmshove/Kluent/tree/numerical-assertions/src/test/kotlin/org/amshove/kluent/tests/assertions/numerical

**Comment by goreRatzete** [comment]
Looking good!

What about something like this for ranges also ?

```
infix fun Number.shouldBeInRange(range: IntRange) = if (range.contains(this)) Unit else throw Exception()

@Test
fun shouldbe() {
    5 shouldBeInRange 4..10

    -100 shouldBeInRange -200..1000

}
```

**Comment by MarkusAmshove** [comment]
You're right, didn't know about that.

There seem to be a couple that we can use:

https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.ranges/index.html

**Comment by goreRatzete** [comment]
Looks good!

**Pull request merged**
