### PR TITLE
Add assertions for sequences

### LINKED ISSUE #149: Assertion for sequences
Hi, 

Almost all assertions available for collections could be available for `Sequence`.

I would be particulary interested in:
```
sequence.shouldBeEmpty()
sequence.shouldNotBeEmpty()
sequence shouldContain "element"
sequence shouldContainSame listOf("a", "b")
```

### PR DESCRIPTION
**Pull request by jcornaz**
Hi, 

Thi PR adds assertions for sequences.

Resolves #149 

- [x] my name is already in the `AUTHORS` file

### CODE REVIEW

**Comment by jcornaz** [comment]
I'm not sure about the `shouldEqual` and `shouldNotEqual`. In one hand it could be useful. In the other it may be astonishing, since it is not consistent with `==`.

Tell me what you think about it. And I'll remove it if necessary.

**Comment by MarkusAmshove** [comment]
Thanks for the PR, I'll have time to look into it at the weekend.

I think `shouldEqual` should mimic the behaviour of Iterable shouldEqual Iterable.
But it needs to make sure that it doesn't run forever, since Sequences can be infinite

**Comment by MarkusAmshove** [comment]
`sequence shouldEqual sequence` would now resolve to `T shouldEqual T`, which calls `assertEquals` under the hood. 
Can you test if this results in anything useful? If not, we should definitely add custom behavior to prevent confusion :-)

**Comment by jcornaz** [comment]
Hi @MarkusAmshove, 

After some thought I don't think equality check make sense for sequences.

I think one should use `shouldContainSame` or have explicti `toList()`.

Otherwise reading `seq1 shouldEqual seq2` should be hard to interpret for newcommers since `Sequence` do not normally support equality check.

**Comment by MarkusAmshove** [comment]
That makes sense, but should we have an overload for Sequences and `shouldEqual` that throws to let the user know that it doesn't make sense and they should use another assertion?

Because there is `Any.shouldEqual(Any)`, so the method *would* be available for Sequences :-)

**Comment by jcornaz** [comment]
>should we have an overload for Sequences and shouldEqual that throws to let the user know that it doesn't make sense and they should use another assertion?

Interesting idea. Yeah it'd be nice I think. I'll add this overload.

**Comment by jcornaz** [comment]
I made the change preventing usage of `shouldEqual` and `shouldNotEqual` on sequences.

**Comment by MarkusAmshove** [comment]
This is now released within 1.57

**Pull request merged**
